const data = [
    {
      id: 1,
      img: "url_imagen_1",
      Nombredeflor: "Rosa",
      precio: 32000,
      categoria: "Silver",
      cantidadUnidades: 50,
    },


    {
      id: 2,
      img: "url_imagen_2",
      Nombredeflor: "Lirio",
      precio: 25500,
      categoria: "Silver",
      cantidadUnidades: 30,
    },
    {
      id: 3,
      img: "url_imagen_3",
      Nombredeflor: "Tulipán",
      precio: 55000,
      categoria: "Gold",
      cantidadUnidades: 10,
    },
    {
      id: 4,
      img: "url_imagen_4",
      Nombredeflor: "Orquídea",
      precio: 78000,
      categoria: "Platinum",
      cantidadUnidades: 20,
    },
    {
      id: 5,
      img: "url_imagen_5",
      Nombredeflor: "Girasol",
      precio: 42000,
      categoria: "Gold",
      cantidadUnidades: 15,
    },
    {
      id: 6,
      img: "url_imagen_6",
      Nombredeflor: "Margarita",
      precio: 18000,
      categoria: "Silver",
      cantidadUnidades: 40,
    },
    {
      id: 7,
      img: "url_imagen_7",
      Nombredeflor: "Amapola",
      precio: 32000,
      categoria: "Silver",
      cantidadUnidades: 25,
    },
    {
      id: 8,
      img: "url_imagen_8",
      Nombredeflor: "Clavel",
      precio: 29000,
      categoria: "Gold",
      cantidadUnidades: 18,
    },
    {
      id: 9,
      img: "url_imagen_9",
      Nombredeflor: "Azucena",
      precio: 60000,
      categoria: "Platinum",
      cantidadUnidades: 12,
    },
    {
      id: 10,
      img: "url_imagen_10",
      Nombredeflor: "Lavanda",
      precio: 48000,
      categoria: "Gold",
      cantidadUnidades: 22,
    },
    {
      id: 11,
      img: "url_imagen_11",
      Nombredeflor: "Caléndula",
      precio: 35000,
      categoria: "Silver",
      cantidadUnidades: 28,
    },
    {
      id: 12,
      img: "url_imagen_12",
      Nombredeflor: "Dalia",
      precio: 43000,
      categoria: "Gold",
      cantidadUnidades: 24,
    },
    {
      id: 13,
      img: "url_imagen_13",
      Nombredeflor: "Peonía",
      precio: 51000,
      categoria: "Platinum",
      cantidadUnidades: 8,
    },
    {
      id: 14,
      img: "url_imagen_14",
      Nombredeflor: "Hortensia",
      precio: 67000,
      categoria: "Platinum",
      cantidadUnidades: 15,
    },
    {
      id: 15,
      img: "url_imagen_15",
      Nombredeflor: "Crótalo",
      precio: 32000,
      categoria: "Silver",
      cantidadUnidades: 36,
    },
    {
      id: 16,
      img: "url_imagen_16",
      Nombredeflor: "Aster",
      precio: 40000,
      categoria: "Gold",
      cantidadUnidades: 14,
    },
    {
      id: 17,
      img: "url_imagen_17",
      Nombredeflor: "Begonia",
      precio: 37000,
      categoria: "Silver",
      cantidadUnidades: 32,
    },
    {
      id: 18,
      img: "url_imagen_18",
      Nombredeflor: "Camelia",
      precio: 59000,
      categoria: "Platinum",
      cantidadUnidades: 10,
    },
    {
      id: 19,
      img: "url_imagen_19",
      Nombredeflor: "Diente de león",
      precio: 34000,
      categoria: "Silver",
      cantidadUnidades: 28,
    },
    {
      id: 20,
      img: "url_imagen_20",
      Nombredeflor: "Eustoma",
      precio: 45000,
      categoria: "Gold",
      cantidadUnidades: 20,
    },
    {
      id: 21,
      img: "url_imagen_21",
      Nombredeflor: "Freesia",
      precio: 48000,
      categoria: "Gold",
      cantidadUnidades: 18,
    },
    {
      id: 22,
      img: "url_imagen_22",
      Nombredeflor: "Geranio",
      precio: 39000,
      categoria: "Silver",
      cantidadUnidades: 25,
    },
    {
      id: 23,
      img: "url_imagen_23",
      Nombredeflor: "Hibisco",
      precio: 55000,
      categoria: "Gold",
      cantidadUnidades: 15,
    },
    {
      id: 24,
      img: "url_imagen_24",
      Nombredeflor: "Iris",
      precio: 43000,
      categoria: "Silver",
      cantidadUnidades: 30,
    },
    {
      id: 25,
      img: "url_imagen_25",
      Nombredeflor: "Jacinto",
      precio: 60000,
      categoria: "Platinum",
      cantidadUnidades: 12,
    },
    {
      id: 26,
      img: "url_imagen_26",
      Nombredeflor: "Lavatera",
      precio: 35000,
      categoria: "Silver",
      cantidadUnidades: 32,
    },
    {
      id: 27,
      img: "url_imagen_27",
      Nombredeflor: "Malva",
      precio: 42000,
      categoria: "Gold",
      cantidadUnidades: 20,
    },
    {
      id: 28,
      img: "url_imagen_28",
      Nombredeflor: "Narciso",
      precio: 50000,
      categoria: "Platinum",
      cantidadUnidades: 14,
    },
    {
      id: 29,
      img: "url_imagen_29",
      Nombredeflor: "Ostica",
      precio: 28000,
      categoria: "Silver",
      cantidadUnidades: 40,
    },
    {
      id: 30,
      img: "url_imagen_30",
      Nombredeflor: "Petunia",
      precio: 39000,
      categoria: "Gold",
      cantidadUnidades: 22,
    },
    {
      id: 31,
      img: "url_imagen_31",
      Nombredeflor: "Quinto",
      precio: 34000,
      categoria: "Silver",
      cantidadUnidades: 28,
    },
    {
      id: 32,
      img: "url_imagen_32",
      Nombredeflor: "Roselina",
      precio: 59000,
      categoria: "Platinum",
      cantidadUnidades: 10,
    },
    {
      id: 33,
      img: "url_imagen_33",
      Nombredeflor: "Santapaz",
      precio: 47000,
      categoria: "Gold",
      cantidadUnidades: 18,
    },
    {
      id: 34,
      img: "url_imagen_34",
      Nombredeflor: "Trevir",
      precio: 38000,
      categoria: "Silver",
      cantidadUnidades: 25,
    },
    {
      id: 35,
      img: "url_imagen_35",
      Nombredeflor: "Ursalia",
      precio: 62000,
      categoria: "Platinum",
      cantidadUnidades: 8,
    },
    {
      id: 36,
      img: "url_imagen_36",
      Nombredeflor: "Violeta",
      precio: 30000,
      categoria: "Silver",
      cantidadUnidades: 35,
    },
    {
      id: 37,
      img: "url_imagen_37",
      Nombredeflor: "Wisteria",
      precio: 53000,
      categoria: "Gold",
      cantidadUnidades: 16,
    },
    {
      id: 38,
      img: "url_imagen_38",
      Nombredeflor: "Xavier",
      precio: 46000,
      categoria: "Silver",
      cantidadUnidades: 24,
    },
    {
      id: 39,
      img: "url_imagen_39",
      Nombredeflor: "Yasmin",
      precio: 52000,
      categoria: "Gold",
      cantidadUnidades: 14,
    },
    {
      id: 40,
      img: "url_imagen_40",
      Nombredeflor: "Zinia",
      precio: 40000,
      categoria: "Silver",
      cantidadUnidades: 30,
    },
    {
      id: 41,
      img: "url_imagen_41",
      Nombredeflor: "Alhelí",
      precio: 35000,
      categoria: "Gold",
      cantidadUnidades: 18,
    },
    {
      id: 42,
      img: "url_imagen_42",
      Nombredeflor: "Bambú",
      precio: 59000,
      categoria: "Platinum",
      cantidadUnidades: 12,
    },
    {
      id: 43,
      img: "url_imagen_43",
      Nombredeflor: "Campanilla",
      precio: 51000,
      categoria: "Gold",
      cantidadUnidades:11,
    },
    {
    id: 44,
    img: "url_imagen_51",
    Nombredeflor: "Flor51",
    precio: 42000,
    categoria: "Silver",
    cantidadUnidades: 25,
  },
  {
    id: 45,
    img: "url_imagen_52",
    Nombredeflor: "Flor52",
    precio: 38000,
    categoria: "Platinum",
    cantidadUnidades: 20,
  },
  {
    id: 46,
    img: "url_imagen_53",
    Nombredeflor: "Flor53",
    precio: 46000,
    categoria: "Silver",
    cantidadUnidades: 15,
  },
  {
    id: 47,
    img: "url_imagen_54",
    Nombredeflor: "Flor54",
    precio: 49000,
    categoria: "Gold",
    cantidadUnidades: 18,
  },
  {
    id: 48,
    img: "url_imagen_55",
    Nombredeflor: "Flor55",
    precio: 34000,
    categoria: "Silver",
    cantidadUnidades: 30,
  },
  {
    id: 49,
    img: "url_imagen_56",
    Nombredeflor: "Flor56",
    precio: 58000,
    categoria: "Gold",
    cantidadUnidades: 12,
  },
  {
    id: 50,
    img: "url_imagen_57",
    Nombredeflor: "Flor57",
    precio: 41000,
    categoria: "Platinum",
    cantidadUnidades: 22,
  }
  
];

// Función para llenar la estructura con datos del arreglo
function llenarTarjetasConDatosDelArreglo() {
  const tarjetas = document.querySelectorAll(".targetas__car");

  // Iterar sobre las tarjetas y los datos en el arreglo
  tarjetas.forEach((tarjeta, index) => {
    const div = tarjeta.querySelector("div");

    // Obtener los datos del arreglo usando el índice
    const { categoria, precio, Nombredeflor, cantidadUnidades } = data[index];

    // Asignar los datos a los elementos p dentro del div
    div.children[0].textContent = "Categoria: " + categoria;
    div.children[1].textContent = "Precio: $" + precio;
    div.children[2].textContent = "Especie: " + Nombredeflor;
    div.children[3].textContent = "Cantidad: " + cantidadUnidades;
    div.children[4].textContent = "Disponible: " + (Math.random() > 0.5 ? "Sí" : "No");
  });
}

// Llamada a la función para llenar las tarjetas con datos del arreglo al cargar la página
window.onload = llenarTarjetasConDatosDelArreglo;

